# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_client.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.group_btn = QtWidgets.QGroupBox(self.centralwidget)
        self.group_btn.setObjectName("group_btn")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_btn)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_connect = QtWidgets.QPushButton(self.group_btn)
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout.addWidget(self.btn_connect)
        self.btn_login = QtWidgets.QPushButton(self.group_btn)
        self.btn_login.setEnabled(False)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        self.btn_syst = QtWidgets.QPushButton(self.group_btn)
        self.btn_syst.setEnabled(False)
        self.btn_syst.setObjectName("btn_syst")
        self.verticalLayout.addWidget(self.btn_syst)
        self.btn_type = QtWidgets.QPushButton(self.group_btn)
        self.btn_type.setEnabled(False)
        self.btn_type.setObjectName("btn_type")
        self.verticalLayout.addWidget(self.btn_type)
        self.rb_port = QtWidgets.QRadioButton(self.group_btn)
        self.rb_port.setEnabled(False)
        self.rb_port.setObjectName("rb_port")
        self.verticalLayout.addWidget(self.rb_port)
        self.rb_pasv = QtWidgets.QRadioButton(self.group_btn)
        self.rb_pasv.setEnabled(False)
        self.rb_pasv.setChecked(True)
        self.rb_pasv.setObjectName("rb_pasv")
        self.verticalLayout.addWidget(self.rb_pasv)
        self.btn_list = QtWidgets.QPushButton(self.group_btn)
        self.btn_list.setEnabled(False)
        self.btn_list.setObjectName("btn_list")
        self.verticalLayout.addWidget(self.btn_list)
        self.btn_mkd = QtWidgets.QPushButton(self.group_btn)
        self.btn_mkd.setEnabled(False)
        self.btn_mkd.setObjectName("btn_mkd")
        self.verticalLayout.addWidget(self.btn_mkd)
        self.btn_rename = QtWidgets.QPushButton(self.group_btn)
        self.btn_rename.setEnabled(False)
        self.btn_rename.setObjectName("btn_rename")
        self.verticalLayout.addWidget(self.btn_rename)
        self.btn_dele = QtWidgets.QPushButton(self.group_btn)
        self.btn_dele.setEnabled(False)
        self.btn_dele.setObjectName("btn_dele")
        self.verticalLayout.addWidget(self.btn_dele)
        self.btn_upload = QtWidgets.QPushButton(self.group_btn)
        self.btn_upload.setEnabled(False)
        self.btn_upload.setObjectName("btn_upload")
        self.verticalLayout.addWidget(self.btn_upload)
        self.btn_download = QtWidgets.QPushButton(self.group_btn)
        self.btn_download.setEnabled(False)
        self.btn_download.setObjectName("btn_download")
        self.verticalLayout.addWidget(self.btn_download)
        self.btn_quit = QtWidgets.QPushButton(self.group_btn)
        self.btn_quit.setEnabled(False)
        self.btn_quit.setObjectName("btn_quit")
        self.verticalLayout.addWidget(self.btn_quit)
        self.horizontalLayout_2.addWidget(self.group_btn)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_send = QtWidgets.QPushButton(self.tab)
        self.btn_send.setEnabled(False)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout.addWidget(self.btn_send)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree = QtWidgets.QTreeWidget(self.tab_2)
        self.tree.setEnabled(False)
        self.tree.setObjectName("tree")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree.headerItem().setFont(0, font)
        self.gridLayout_2.addWidget(self.tree, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client"))
        self.group_btn.setTitle(_translate("MainWindow", "Tool Button"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.btn_syst.setText(_translate("MainWindow", "SYST"))
        self.btn_type.setText(_translate("MainWindow", "TYPE"))
        self.rb_port.setText(_translate("MainWindow", "Active"))
        self.rb_pasv.setText(_translate("MainWindow", "Passive"))
        self.btn_list.setText(_translate("MainWindow", "LIST"))
        self.btn_mkd.setText(_translate("MainWindow", "New dir"))
        self.btn_rename.setText(_translate("MainWindow", "Rename"))
        self.btn_dele.setText(_translate("MainWindow", "Delete"))
        self.btn_upload.setText(_translate("MainWindow", "Upload"))
        self.btn_download.setText(_translate("MainWindow", "Download"))
        self.btn_quit.setText(_translate("MainWindow", "QUIT"))
        self.btn_send.setText(_translate("MainWindow", "Send"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Welcome to FTP Client!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Click Connect to begin~</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#0000ff;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Command Line Tool"))
        self.tree.headerItem().setText(0, _translate("MainWindow", "名称"))
        self.tree.headerItem().setText(1, _translate("MainWindow", "大小"))
        self.tree.headerItem().setText(2, _translate("MainWindow", "修改时间"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tree View"))

